import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';

export default function Dashboard() {
  const [stats, setStats] = useState(null);
    const [history, setHistory] = useState([]);
      const [pendingCount, setPendingCount] = useState(0);
        const [loading, setLoading] = useState(true);
          const [error, setError] = useState('');

            useEffect(() => {
                Promise.all([
                      axios.get('/api/stats'),
                            axios.get('/api/stats/history'),
                                  axios.get('/api/posts?status=pending')
                                      ])
                                            .then(([statsRes, historyRes, postsRes]) => {
                                                    setStats(statsRes.data);
                                                            // Formater l'historique pour recharts
                                                                    const formatted = historyRes.data.history.reverse().map((h, i) => ({
                                                                              name: `J-${historyRes.data.history.length - 1 - i}`,
                                                                                        Followers: h.followers_count,
                                                                                                  Likes: h.likes_count
                                                                                                          }));
                                                                                                                  setHistory(formatted);
                                                                                                                          setPendingCount(postsRes.data.posts.length);
                                                                                                                                })
                                                                                                                                      .catch(() => setError('Impossible de charger les statistiques'))
                                                                                                                                            .finally(() => setLoading(false));
                                                                                                                                              }, []);

                                                                                                                                                if (loading) {
                                                                                                                                                    return (
                                                                                                                                                          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '60vh' }}>
                                                                                                                                                                  <div className="spinner" />
                                                                                                                                                                        </div>
                                                                                                                                                                            );
                                                                                                                                                                              }

                                                                                                                                                                                if (error) {
                                                                                                                                                                                    return <div className="alert alert-error">{error}</div>;
                                                                                                                                                                                      }

                                                                                                                                                                                        const fmt = n => n >= 1000000
                                                                                                                                                                                            ? (n / 1000000).toFixed(1) + 'M'
                                                                                                                                                                                                : n >= 1000 ? (n / 1000).toFixed(1) + 'K'
                                                                                                                                                                                                    : n?.toString() || '0';

                                                                                                                                                                                                      const CustomTooltip = ({ active, payload, label }) => {
                                                                                                                                                                                                          if (active && payload && payload.length) {
                                                                                                                                                                                                                return (
                                                                                                                                                                                                                        <div style={{
                                                                                                                                                                                                                                  background: 'var(--bg3)', border: '1px solid var(--border)',
                                                                                                                                                                                                                                            borderRadius: '10px', padding: '12px 16px', fontSize: '13px'
                                                                                                                                                                                                                                                    }}>
                                                                                                                                                                                                                                                              <p style={{ color: 'var(--text2)', marginBottom: '6px' }}>{label}</p>
                                                                                                                                                                                                                                                                        {payload.map(p => (
                                                                                                                                                                                                                                                                                    <p key={p.name} style={{ color: p.color }}>
                                                                                                                                                                                                                                                                                                  {p.name}: <strong>{fmt(p.value)}</strong>
                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                              return null;
                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                            <div className="page-header fade-up">
                                                                                                                                                                                                                                                                                                                                                                    <div className="page-title">Dashboard</div>
                                                                                                                                                                                                                                                                                                                                                                            <div className="page-subtitle">Vue d'ensemble de ton compte TikTok</div>
                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                        {/* Stats cards */}
                                                                                                                                                                                                                                                                                                                                                                                              <div className="card-grid fade-up-1" style={{ marginBottom: '28px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                      {[
                                                                                                                                                                                                                                                                                                                                                                                                                { label: 'Followers', value: fmt(stats?.followers), icon: '👥', color: 'var(--pink)' },
                                                                                                                                                                                                                                                                                                                                                                                                                          { label: 'Likes totaux', value: fmt(stats?.likes), icon: '❤️', color: '#ff6b6b' },
                                                                                                                                                                                                                                                                                                                                                                                                                                    { label: 'Vidéos', value: stats?.videos || 0, icon: '🎬', color: 'var(--cyan)' },
                                                                                                                                                                                                                                                                                                                                                                                                                                              { label: 'Posts planifiés', value: pendingCount, icon: '📅', color: '#ffc800' }
                                                                                                                                                                                                                                                                                                                                                                                                                                                      ].map((s, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div key={s.label} className="stat-card" style={{ animationDelay: `${i * 0.08}s` }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="stat-label">{s.label}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="stat-value" style={{ color: s.color }}>{s.value}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="stat-icon">{s.icon}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Graphique followers */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {history.length > 1 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="card fade-up-2" style={{ marginBottom: '24px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontFamily: 'var(--font-display)', fontSize: '16px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontWeight: '700', marginBottom: '24px'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Évolution des followers
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <ResponsiveContainer width="100%" height={220}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <LineChart data={history}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <XAxis dataKey="name" stroke="var(--text2)" fontSize={12} tickLine={false} axisLine={false} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <YAxis stroke="var(--text2)" fontSize={12} tickLine={false} axisLine={false} tickFormatter={fmt} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Tooltip content={<CustomTooltip />} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Line
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type="monotone" dataKey="Followers"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                stroke="var(--pink)" strokeWidth={2.5}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                dot={false} activeDot={{ r: 5, fill: 'var(--pink)' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </LineChart>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </ResponsiveContainer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Profil */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="card fade-up-3" style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {stats?.avatar_url && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <img src={stats.avatar_url} alt="" style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            width: '56px', height: '56px', borderRadius: '50%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border: '2px solid var(--pink)'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '18px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @{stats?.display_name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ color: 'var(--text2)', fontSize: '13px', marginTop: '4px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {fmt(stats?.following)} abonnements · Compte connecté ✅
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      