const cron = require('node-cron');
const axios = require('axios');
const fs = require('fs');
const FormData = require('form-data');
const { pool } = require('../db');

// ─────────────────────────────────────────────
// Publie une vidéo sur TikTok via l'API Direct Post
// ─────────────────────────────────────────────
async function publishToTikTok(post, accessToken) {
  const videoPath = post.video_path;

    if (!fs.existsSync(videoPath)) {
        throw new Error(`Fichier vidéo introuvable : ${videoPath}`);
          }

            const videoBuffer = fs.readFileSync(videoPath);
              const videoSize = fs.statSync(videoPath).size;

                // Étape 1 : Initialisation de l'upload
                  const initResponse = await axios.post(
                      'https://open.tiktokapis.com/v2/post/publish/video/init/',
                          {
                                post_info: {
                                        title: buildCaption(post),
                                                privacy_level: 'PUBLIC_TO_EVERYONE',
                                                        disable_duet: false,
                                                                disable_comment: false,
                                                                        disable_stitch: false
                                                                              },
                                                                                    source_info: {
                                                                                            source: 'FILE_UPLOAD',
                                                                                                    video_size: videoSize,
                                                                                                            chunk_size: videoSize,
                                                                                                                    total_chunk_count: 1
                                                                                                                          }
                                                                                                                              },
                                                                                                                                  {
                                                                                                                                        headers: {
                                                                                                                                                Authorization: `Bearer ${accessToken}`,
                                                                                                                                                        'Content-Type': 'application/json; charset=UTF-8'
                                                                                                                                                              }
                                                                                                                                                                  }
                                                                                                                                                                    );

                                                                                                                                                                      const { publish_id, upload_url } = initResponse.data.data;

                                                                                                                                                                        // Étape 2 : Upload de la vidéo
                                                                                                                                                                          await axios.put(upload_url, videoBuffer, {
                                                                                                                                                                              headers: {
                                                                                                                                                                                    'Content-Type': 'video/mp4',
                                                                                                                                                                                          'Content-Range': `bytes 0-${videoSize - 1}/${videoSize}`,
                                                                                                                                                                                                'Content-Length': videoSize
                                                                                                                                                                                                    }
                                                                                                                                                                                                      });

                                                                                                                                                                                                        return publish_id;
                                                                                                                                                                                                        }

                                                                                                                                                                                                        // Construit la légende avec les hashtags
                                                                                                                                                                                                        function buildCaption(post) {
                                                                                                                                                                                                          let caption = post.caption || '';
                                                                                                                                                                                                            if (post.hashtags && post.hashtags.length > 0) {
                                                                                                                                                                                                                caption += ' ' + post.hashtags.map(h => `#${h}`).join(' ');
                                                                                                                                                                                                                  }
                                                                                                                                                                                                                    return caption.trim();
                                                                                                                                                                                                                    }

                                                                                                                                                                                                                    // ─────────────────────────────────────────────
                                                                                                                                                                                                                    // Vérifie et rafraîchit le token si nécessaire
                                                                                                                                                                                                                    // ─────────────────────────────────────────────
                                                                                                                                                                                                                    async function getValidToken(userId) {
                                                                                                                                                                                                                      const result = await pool.query(
                                                                                                                                                                                                                          'SELECT access_token, refresh_token, token_expires_at FROM users WHERE id = $1',
                                                                                                                                                                                                                              [userId]
                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                  if (!result.rows.length) throw new Error('Utilisateur introuvable');

                                                                                                                                                                                                                                    const user = result.rows[0];
                                                                                                                                                                                                                                      const now = new Date();
                                                                                                                                                                                                                                        const expiresAt = new Date(user.token_expires_at);

                                                                                                                                                                                                                                          // Rafraîchissement si le token expire dans moins d'1 heure
                                                                                                                                                                                                                                            if (expiresAt - now < 3600 * 1000) {
                                                                                                                                                                                                                                                const refreshResponse = await axios.post('https://open.tiktokapis.com/v2/oauth/token/', {
                                                                                                                                                                                                                                                      client_key: process.env.TIKTOK_CLIENT_KEY,
                                                                                                                                                                                                                                                            client_secret: process.env.TIKTOK_CLIENT_SECRET,
                                                                                                                                                                                                                                                                  grant_type: 'refresh_token',
                                                                                                                                                                                                                                                                        refresh_token: user.refresh_token
                                                                                                                                                                                                                                                                            }, {
                                                                                                                                                                                                                                                                                  headers: { 'Content-Type': 'application/x-www-form-urlencoded' }
                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                          const { access_token, refresh_token, expires_in } = refreshResponse.data;
                                                                                                                                                                                                                                                                                              const newExpiry = new Date(Date.now() + expires_in * 1000);

                                                                                                                                                                                                                                                                                                  await pool.query(
                                                                                                                                                                                                                                                                                                        'UPDATE users SET access_token = $1, refresh_token = $2, token_expires_at = $3 WHERE id = $4',
                                                                                                                                                                                                                                                                                                              [access_token, refresh_token, newExpiry, userId]
                                                                                                                                                                                                                                                                                                                  );

                                                                                                                                                                                                                                                                                                                      return access_token;
                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                          return user.access_token;
                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                          // ─────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                          // CRON : toutes les minutes, publie les posts en attente
                                                                                                                                                                                                                                                                                                                          // ─────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                          function startScheduler() {
                                                                                                                                                                                                                                                                                                                            cron.schedule('* * * * *', async () => {
                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                      // Récupère tous les posts à publier maintenant
                                                                                                                                                                                                                                                                                                                                            const result = await pool.query(`
                                                                                                                                                                                                                                                                                                                                                    SELECT * FROM scheduled_posts
                                                                                                                                                                                                                                                                                                                                                            WHERE status = 'pending'
                                                                                                                                                                                                                                                                                                                                                                    AND scheduled_at <= NOW()
                                                                                                                                                                                                                                                                                                                                                                            ORDER BY scheduled_at ASC
                                                                                                                                                                                                                                                                                                                                                                                    LIMIT 10
                                                                                                                                                                                                                                                                                                                                                                                          `);

                                                                                                                                                                                                                                                                                                                                                                                                if (result.rows.length === 0) return;

                                                                                                                                                                                                                                                                                                                                                                                                      console.log(`📅 ${result.rows.length} post(s) à publier...`);

                                                                                                                                                                                                                                                                                                                                                                                                            for (const post of result.rows) {
                                                                                                                                                                                                                                                                                                                                                                                                                    // Marque en cours pour éviter les doublons
                                                                                                                                                                                                                                                                                                                                                                                                                            await pool.query(
                                                                                                                                                                                                                                                                                                                                                                                                                                      "UPDATE scheduled_posts SET status = 'processing' WHERE id = $1",
                                                                                                                                                                                                                                                                                                                                                                                                                                                [post.id]
                                                                                                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const accessToken = await getValidToken(post.user_id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const publishId = await publishToTikTok(post, accessToken);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Succès
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await pool.query(`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    UPDATE scheduled_posts
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                SET status = 'published', tiktok_post_id = $1, updated_at = NOW()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            WHERE id = $2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      `, [publishId, post.id]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log(`✅ Post #${post.id} publié sur TikTok (publish_id: ${publishId})`);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Suppression du fichier vidéo local après publication
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (post.video_path && fs.existsSync(post.video_path)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fs.unlinkSync(post.video_path);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Échec de publication
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.error(`❌ Erreur publication post #${post.id}:`, err.message);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await pool.query(`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            UPDATE scheduled_posts
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        SET status = 'failed', error_message = $1, updated_at = NOW()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    WHERE id = $2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              `, [err.message, post.id]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.error('❌ Erreur scheduler:', err.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log('⏰ Scheduler démarré — vérification toutes les minutes');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              module.exports = { startScheduler };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              